<a href="https://colab.research.google.com/github/Saifparihar/PLAY-STORE-APP-REVIEW-ANALYSIS/blob/main/PLAY_STORE_APP_REVIEW_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project Name**    - PLAY STORE APP REVIEW ANALYSIS



##### **Project Type**    - EDA
##### **Contribution**    - Individual
##### **Team Member 1 -**  Saif Ali Parihar


# **Project Summary -**

Write the summary here within 500-600 words.

# **GitHub Link -**

https://github.com/Saifparihar/PLAY-STORE-APP-REVIEW-ANALYSIS

# **Problem Statement**


**Write Problem Statement Here.**

#### **Define Your Business Objective?**

Answer Here.

# **General Guidelines** : -  

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]





# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
from datetime import datetime
import seaborn as sns

### Dataset Loading

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [94]:
# Importing Play Store App Review Dataset
df1 = pd.read_csv('/content/drive/MyDrive/Almabetter Projects/EDA/Play Store Data.csv')

In [95]:
# Importing Play Store App Sentiment Data ## Customer Review Data
df2=pd.read_csv('/content/drive/MyDrive/Almabetter Projects/EDA/User Reviews.csv')

### Dataset First View

In [96]:
df1.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [97]:
df1.tail()

App             Category  \
10836                               Sya9a Maroc - FR               FAMILY   
10837               Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                         Parkinson Exercices FR              MEDICAL   
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating             Genres      Last Updated         Current Ver  \
10836       Everyone          Education     July 25, 2017                1.48   
10837       Everyone          Education      July 6, 2018                 1.0   
10838       Everyone            Medical  January 20, 2017                 1.0   
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device   
10840       Everyone          Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
10836          4.1 and up  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device

### Dataset Rows & Columns count

In [98]:
num_rows = df1.shape[0]
num_columns = df1.shape[1]


print("Play Store Dataset size(First Data frame)")
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Play Store Dataset size(First Data frame)
Number of rows: 10841
Number of columns: 13


### Dataset Information

In [99]:
# Dataset Info
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10841 non-null  object 
 1   Category        10841 non-null  object 
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object 
 4   Size            10841 non-null  object 
 5   Installs        10841 non-null  object 
 6   Type            10840 non-null  object 
 7   Price           10841 non-null  object 
 8   Content Rating  10840 non-null  object 
 9   Genres          10841 non-null  object 
 10  Last Updated    10841 non-null  object 
 11  Current Ver     10833 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(1), object(12)
memory usage: 1.1+ MB


#### Duplicate Values

In [100]:
# Dataset Duplicate Value Count
len(df1[df1.duplicated()])

483

In [101]:
# Dropping the duplicate values from Play store dataset.
df1= df1.drop_duplicates()

In [102]:
# Rechecking the shape of our play store dataset after dropping all the duplicates.
df1.shape

(10358, 13)

#### Missing Values/Null Values

In [103]:
# Missing Values/Null Values Count
df1.isnull().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [104]:
# Visualizing the missing values
sns.heatmap(df1.isnull(), cmap='viridis')
plt.title('Missing Values Heatmap')
#As we can see, the rating column is the only one showing a relation with yellow strips because it is the only one with as many as 1474 null values

Text(0.5, 1.0, 'Missing Values Heatmap')

### What did you know about your dataset?

I discovered that the Play Store dataset comprises 13 columns and 10,841 rows. Within this dataset, there were some duplicate values, totaling 483, which I removed to enhance data cleanliness. Additionally, the 'rating' column has 1,474 null values. The objective is to analyze the competition in the Android market using Play Store application data

## ***2. Understanding Your Variables***

In [105]:
# Dataset Columns
df1.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [106]:
# Dataset Describe
df1.describe(include = 'all')

App Category       Rating Reviews                Size    Installs  \
count    10358    10358  8893.000000   10358               10358       10358   
unique    9660       34          NaN    6002                 462          22   
top     ROBLOX   FAMILY          NaN       0  Varies with device  1,000,000+   
freq         9     1943          NaN     593                1526        1488   
mean       NaN      NaN     4.189542     NaN                 NaN         NaN   
std        NaN      NaN     0.545452     NaN                 NaN         NaN   
min        NaN      NaN     1.000000     NaN                 NaN         NaN   
25%        NaN      NaN     4.000000     NaN                 NaN         NaN   
50%        NaN      NaN     4.300000     NaN                 NaN         NaN   
75%        NaN      NaN     4.500000     NaN                 NaN         NaN   
max        NaN      NaN    19.000000     NaN                 NaN         NaN   

         Type  Price Content Rating Genres    Last Updated  \
count   10357  10358          10357  10358           10358   
unique      3     93              6    120            1378   
top      Free      0       Everyone  Tools  August 3, 2018   
freq     9591   9592           8382    842             298   
mean      NaN    NaN            NaN    NaN             NaN   
std       NaN    NaN            NaN    NaN             NaN   
min       NaN    NaN            NaN    NaN             NaN   
25%       NaN    NaN            NaN    NaN             NaN   
50%       NaN    NaN            NaN    NaN             NaN   
75%       NaN    NaN            NaN    NaN             NaN   
max       NaN    NaN            NaN    NaN             NaN   

               Current Ver Android Ver  
count                10350       10355  
unique                2832          33  
top     Varies with device  4.1 and up  
freq                  1302        2379  
mean                   NaN         NaN  
std                    NaN         NaN  
min                    NaN         NaN  
25%                    NaN         NaN  
50%                    NaN         NaN  
75%                    NaN         NaN  
max                    NaN         NaN

### Variables Description

This file contains data on Google Play applications. It consists of 10,841 rows of data, and it encompasses the following columns:

**App Category**: This indicates the category of the app, which can range from beauty and business to entertainment and education, among others.

**Rating**: Users' evaluations of the app on a scale of 1 to 5, with 1 representing the lowest rating and 5 being the highest.

**Reviews**: The number of user reviews received by each app.

**Size**: The amount of memory required to install the application.

**Installs**: The count of times each application has been installed by users.

**Type**: This field indicates whether the app is available for free or is a paid application.

**Price**: The cost of the app, if it's not free.

**Content Rating**: This column specifies the intended audience for the app, such as teens, mature audiences, or everyone.

**Genres**: Sub-categories for each app. For example, within the Education category, you might find genres like 'Education: Pretend Play'.

**Last Updated**: The release date of the most recent update for the app.

**Current Ver**: The current version of the app.

**Android Ver**: The oldest version of the Android operating system supported by the app.


### Check Unique Values for each variable.

In [107]:
for column in df1.columns:
  unique_values = df1[column].nunique()
  print(f"No. of unique values in column {column} is {unique_values}.")

No. of unique values in column App is 9660.
No. of unique values in column Category is 34.
No. of unique values in column Rating is 40.
No. of unique values in column Reviews is 6002.
No. of unique values in column Size is 462.
No. of unique values in column Installs is 22.
No. of unique values in column Type is 3.
No. of unique values in column Price is 93.
No. of unique values in column Content Rating is 6.
No. of unique values in column Genres is 120.
No. of unique values in column Last Updated is 1378.
No. of unique values in column Current Ver is 2832.
No. of unique values in column Android Ver is 33.


## 3. ***Data Wrangling***

### Data Wrangling Code

 **CLEANING THE DATA**

**A) CHECKING DATATYPE**

In [108]:
pd.DataFrame(df1.dtypes).rename(columns= {0: 'data_type'})

data_type
App               object
Category          object
Rating           float64
Reviews           object
Size              object
Installs          object
Type              object
Price             object
Content Rating    object
Genres            object
Last Updated      object
Current Ver       object
Android Ver       object

**1) REVIEWS**

In [109]:
reviews_counts = df1["Reviews"].value_counts().reset_index()
reviews_counts.columns = ["Number of Reviews", "Count"]
reviews_counts

Number of Reviews  Count
0                    0    593
1                    1    272
2                    2    213
3                    3    170
4                    4    137
...                ...    ...
5997            527247      1
5998            240475      1
5999           5282558      1
6000            654418      1
6001            398307      1

[6002 rows x 2 columns]

In [110]:
reviews = [i for i in df1['Reviews']]
def cleaning_review_data(Reviews_list):
  '''
  This Function Converts DataType From Object To Float
  '''
  cleaned_data = []
  for review in Reviews_list:
     if 'M' in review:
       review = review.replace('M','')
       review = float(review)*1000000
       #converting M(Million) value to numeric
     cleaned_data.append(review)
  return cleaned_data

df1['Reviews']=cleaning_review_data(reviews)
df1['Reviews']=df1['Reviews'].astype(float)
df1['Reviews']

0           159.0
1           967.0
2         87510.0
3        215644.0
4           967.0
           ...   
10836        38.0
10837         4.0
10838         3.0
10839       114.0
10840    398307.0
Name: Reviews, Length: 10358, dtype: float64

In [111]:
df1['Reviews'].dtype

dtype('float64')

**2) SIZE**

In [112]:
size_counts = df1["Size"].value_counts().reset_index()
size_counts.columns = ["Size", "Count"]
size_counts


Size  Count
0    Varies with device   1526
1                   11M    188
2                   12M    186
3                   13M    186
4                   14M    182
..                  ...    ...
457                430k      1
458                429k      1
459                200k      1
460                460k      1
461                619k      1

[462 rows x 2 columns]

In [113]:
newSize = []
for row in df1.Size:
    newrow = row[:-1]
    try:
        newSize.append(float(newrow))
    except:
        newSize.append(0)

df1.Size = newSize          #Sizes of applications are converted from string to integer format
df1['Size'].dtype

dtype('float64')

**3) INSTALLS**

In [114]:
df1["Installs"].value_counts()

1,000,000+        1488
10,000,000+       1132
100,000+          1129
10,000+           1033
1,000+             890
100+               710
5,000,000+         683
500,000+           517
50,000+            474
5,000+             469
10+                385
100,000,000+       369
500+               328
50,000,000+        272
50+                204
5+                  82
1+                  67
500,000,000+        61
1,000,000,000+      49
0+                  14
0                    1
Free                 1
Name: Installs, dtype: int64

In [115]:
df1['Installs'] = df1.Installs.str.replace(",", "")
df1['Installs'] = df1.Installs.str.replace("+", "")
df1['Installs'] = df1.Installs.replace("Free", np.nan)
df1['Installs'] = df1['Installs'].astype(float)
df1['Installs'].dtype

<ipython-input-115-3a6e97c3086d>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df1['Installs'] = df1.Installs.str.replace("+", "")


dtype('float64')

**4) PRICE**

In [116]:
df1["Price"].value_counts()

0          9592
$0.99       146
$2.99       125
$1.99        73
$4.99        70
           ... 
$389.99       1
$19.90        1
$1.75         1
$14.00        1
$1.04         1
Name: Price, Length: 93, dtype: int64

In [117]:
df1['Price'] = df1.Price.replace("Everyone",np.nan)
df1['Price'] = df1.Price.str.replace("$","").astype(float)
df1['Price'].dtype

<ipython-input-117-bd02b2447575>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df1['Price'] = df1.Price.str.replace("$","").astype(float)


dtype('float64')

In [118]:
df1.describe()

Rating       Reviews          Size      Installs         Price
count  8893.000000  1.035800e+04  10358.000000  1.035700e+04  10357.000000
mean      4.189542  4.061551e+05     31.783124  1.415776e+07      1.030800
std       0.545452  2.696768e+06     93.511181  8.023955e+07     16.278625
min       1.000000  0.000000e+00      0.000000  0.000000e+00      0.000000
25%       4.000000  3.200000e+01      3.200000  1.000000e+03      0.000000
50%       4.300000  1.683000e+03     10.000000  1.000000e+05      0.000000
75%       4.500000  4.648275e+04     29.000000  1.000000e+06      0.000000
max      19.000000  7.815831e+07   1020.000000  1.000000e+09    400.000000

**B) HANDLING NULL VALUES**

In [119]:
table=pd.DataFrame(index=df1.columns)
table["datatype"]=df1.dtypes
table["not null values"]=df1.count()
table["null value"]=df1.isnull().sum()
table

datatype  not null values  null value
App              object            10358           0
Category         object            10358           0
Rating          float64             8893        1465
Reviews         float64            10358           0
Size            float64            10358           0
Installs        float64            10357           1
Type             object            10357           1
Price           float64            10357           1
Content Rating   object            10357           1
Genres           object            10358           0
Last Updated     object            10358           0
Current Ver      object            10350           8
Android Ver      object            10355           3

**1) RATING**

In [120]:
df1[df1['Rating'].isnull()]

App             Category  Rating  \
23                  Mcqueen Coloring pages       ART_AND_DESIGN     NaN   
113              Wrinkles and rejuvenation               BEAUTY     NaN   
123                 Manicure - nail design               BEAUTY     NaN   
126           Skin Care and Natural Beauty               BEAUTY     NaN   
129    Secrets of beauty, youth and health               BEAUTY     NaN   
...                                    ...                  ...     ...   
10824                            Cardio-FR              MEDICAL     NaN   
10825                   Naruto & Boruto FR               SOCIAL     NaN   
10831             payermonstationnement.fr  MAPS_AND_NAVIGATION     NaN   
10835                             FR Forms             BUSINESS     NaN   
10838               Parkinson Exercices FR              MEDICAL     NaN   

       Reviews  Size  Installs  Type  Price Content Rating  \
23        61.0   7.0  100000.0  Free    0.0       Everyone   
113      182.0   5.7  100000.0  Free    0.0   Everyone 10+   
123      119.0   3.7   50000.0  Free    0.0       Everyone   
126      654.0   7.4  100000.0  Free    0.0           Teen   
129       77.0   2.9   10000.0  Free    0.0     Mature 17+   
...        ...   ...       ...   ...    ...            ...   
10824     67.0  82.0   10000.0  Free    0.0       Everyone   
10825      7.0   7.7     100.0  Free    0.0           Teen   
10831     38.0   9.8    5000.0  Free    0.0       Everyone   
10835      0.0   9.6      10.0  Free    0.0       Everyone   
10838      3.0   9.5    1000.0  Free    0.0       Everyone   

                                Genres        Last Updated Current Ver  \
23     Art & Design;Action & Adventure       March 7, 2018       1.0.0   
113                             Beauty  September 20, 2017         8.0   
123                             Beauty       July 23, 2018         1.3   
126                             Beauty       July 17, 2018        1.15   
129                             Beauty      August 8, 2017         2.0   
...                                ...                 ...         ...   
10824                          Medical       July 31, 2018       2.2.2   
10825                           Social    February 2, 2018         1.0   
10831                Maps & Navigation       June 13, 2018   2.0.148.0   
10835                         Business  September 29, 2016       1.1.5   
10838                          Medical    January 20, 2017         1.0   

      Android Ver  
23     4.1 and up  
113    3.0 and up  
123    4.1 and up  
126    4.1 and up  
129    2.3 and up  
...           ...  
10824  4.4 and up  
10825  4.0 and up  
10831  4.0 and up  
10835  4.0 and up  
10838  2.2 and up  

[1465 rows x 13 columns]

In [121]:
# The "Rating" column has 1474 rows with null values.
# To handle this, instead of dropping the rows, we will replace the null values with the median of the available values.

df1['Rating'].fillna(value=df1['Rating'].median(),inplace=True)

In [122]:
#verifying for the null values
df1['Rating'].isnull().sum()

0

In [123]:
# Sanity Check

# A sanity check was performed to ensure that the number of ratings was not greater than the number of installations.
# As only those who have installed the app can provide a rating.

In [124]:
df1[df1['Rating'] > df1['Installs']]

App           Category  \
649                          Healthy Relationships Guide             DATING   
652                                              PlusOne             DATING   
2422                                           Visualmed            MEDICAL   
2425   Be the Expert in Phlebotomy - Professional Nur...            MEDICAL   
2454                                 KBA-EZ Health Guide            MEDICAL   
...                                                  ...                ...   
10701                                          F-O-Meter             FAMILY   
10708                                        Custos F.O.           BUSINESS   
10745                                            FP Boss            FINANCE   
10764                                  FP Transportation  AUTO_AND_VEHICLES   
10775                                 FQ - Football Quiz             SPORTS   

       Rating  Reviews   Size  Installs  Type  Price Content Rating  \
649       4.3      0.0    8.2       1.0  Free   0.00       Everyone   
652       4.3      0.0   10.0       1.0  Free   0.00     Mature 17+   
2422      4.3      0.0    3.1       1.0  Paid   2.99       Everyone   
2425      4.3      0.0    5.0       1.0  Paid   0.99       Everyone   
2454      5.0      4.0   25.0       1.0  Free   0.00       Everyone   
...       ...      ...    ...       ...   ...    ...            ...   
10701     4.3      0.0    2.8       1.0  Free   0.00     Mature 17+   
10708     4.3      0.0    9.7       1.0  Free   0.00       Everyone   
10745     4.3      1.0    5.8       1.0  Free   0.00       Everyone   
10764     4.3      1.0  885.0       1.0  Free   0.00       Everyone   
10775     4.3      1.0    9.0       1.0  Free   0.00       Everyone   

                Genres    Last Updated Current Ver   Android Ver  
649             Dating   July 31, 2018         2.0  4.0.3 and up  
652             Dating   July 17, 2018       1.1.1    4.2 and up  
2422           Medical  August 1, 2018         1.0    4.1 and up  
2425           Medical   July 24, 2018         1.0  4.0.3 and up  
2454           Medical  August 2, 2018      1.0.72  4.0.3 and up  
...                ...             ...         ...           ...  
10701    Entertainment  August 2, 2018       1.0.1    4.0 and up  
10708         Business   June 20, 2018       4.1.0    4.1 and up  
10745          Finance   July 27, 2018       1.0.2    5.0 and up  
10764  Auto & Vehicles   March 9, 2018      10.0.0    4.0 and up  
10775           Sports    May 29, 2018         1.0    5.0 and up  

[82 rows x 13 columns]

In [125]:
# Removing the values that failed the sanity check.

temp_data = df1[df1['Rating'] > df1['Installs']].index
df1.drop(labels=temp_data,inplace=True)

In [126]:
#verifying
len(df1[df1['Rating'] > df1['Installs']])

0

**2) TYPE**

In [127]:
df1["Type"].value_counts()

Free    9541
Paid     734
0          1
Name: Type, dtype: int64

In [128]:
# The data includes two types of applications: free and paid.
# In one row, the type is recorded as "nan" and the price is 0, indicating that it is a free app.
# To handle this, the "nan" value was changed to "free."

df1['Type'].fillna('Free',inplace=True)

In [129]:
# Verifying the results with a cross-check.

df1['Type'].isnull().sum()

0

**3) CONTENT RATING**

In [130]:
df1["Content Rating"].value_counts()

Everyone           8309
Teen               1141
Mature 17+          444
Everyone 10+        376
Adults only 18+       3
Unrated               2
Name: Content Rating, dtype: int64

In [131]:
df1[df1['Content Rating'].isnull()]

App Category  Rating    Reviews  \
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0  3000000.0   

       Size  Installs Type  Price Content Rating             Genres  \
10472   0.0       NaN    0    NaN            NaN  February 11, 2018   

      Last Updated Current Ver Android Ver  
10472       1.0.19  4.0 and up         NaN

In [132]:
# In some columns, the values are found to be mismatched.
# To handle this, we will drop the entire row.

df1.drop(10472, axis=0)

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating   Reviews  Size    Installs  Type  Price Content Rating  \
0         4.1     159.0  19.0     10000.0  Free    0.0       Everyone   
1         3.9     967.0  14.0    500000.0  Free    0.0       Everyone   
2         4.7   87510.0   8.7   5000000.0  Free    0.0       Everyone   
3         4.5  215644.0  25.0  50000000.0  Free    0.0           Teen   
4         4.3     967.0   2.8    100000.0  Free    0.0       Everyone   
...       ...       ...   ...         ...   ...    ...            ...   
10836     4.5      38.0  53.0      5000.0  Free    0.0       Everyone   
10837     5.0       4.0   3.6       100.0  Free    0.0       Everyone   
10838     4.3       3.0   9.5      1000.0  Free    0.0       Everyone   
10839     4.5     114.0   0.0      1000.0  Free    0.0     Mature 17+   
10840     4.5  398307.0  19.0  10000000.0  Free    0.0       Everyone   

                          Genres      Last Updated         Current Ver  \
0                   Art & Design   January 7, 2018               1.0.0   
1      Art & Design;Pretend Play  January 15, 2018               2.0.0   
2                   Art & Design    August 1, 2018               1.2.4   
3                   Art & Design      June 8, 2018  Varies with device   
4        Art & Design;Creativity     June 20, 2018                 1.1   
...                          ...               ...                 ...   
10836                  Education     July 25, 2017                1.48   
10837                  Education      July 6, 2018                 1.0   
10838                    Medical  January 20, 2017                 1.0   
10839          Books & Reference  January 19, 2015  Varies with device   
10840                  Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
0            4.0.3 and up  
1            4.0.3 and up  
2            4.0.3 and up  
3              4.2 and up  
4              4.4 and up  
...                   ...  
10836          4.1 and up  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device  

[10275 rows x 13 columns]

**4) CURRENT VERSION**

In [133]:
df1[df1['Current Ver'].isnull()]

App             Category  Rating  Reviews  \
15     Learn To Draw Kawaii Characters       ART_AND_DESIGN     3.2     55.0   
1553              Market Update Helper   LIBRARIES_AND_DEMO     4.1  20145.0   
6322            Virtual DJ Sound Mixer                TOOLS     4.2   4010.0   
6803                         BT Master               FAMILY     4.3      0.0   
7333                       Dots puzzle               FAMILY     4.0    179.0   
7407                   Calculate My IQ               FAMILY     4.3     44.0   
7730                            UFO-CQ                TOOLS     4.3      1.0   
10342                   La Fe de Jesus  BOOKS_AND_REFERENCE     4.3      8.0   

        Size   Installs  Type  Price Content Rating             Genres  \
15       2.7     5000.0  Free   0.00       Everyone       Art & Design   
1553    11.0  1000000.0  Free   0.00       Everyone   Libraries & Demo   
6322     8.7   500000.0  Free   0.00       Everyone              Tools   
6803   222.0      100.0  Free   0.00       Everyone          Education   
7333    14.0    50000.0  Paid   0.99       Everyone             Puzzle   
7407     7.2    10000.0  Free   0.00       Everyone      Entertainment   
7730   237.0       10.0  Paid   0.99       Everyone              Tools   
10342  658.0     1000.0  Free   0.00       Everyone  Books & Reference   

            Last Updated Current Ver Android Ver  
15          June 6, 2018         NaN  4.2 and up  
1553   February 12, 2013         NaN  1.5 and up  
6322        May 10, 2017         NaN  4.0 and up  
6803    November 6, 2016         NaN  1.6 and up  
7333      April 18, 2018         NaN  4.0 and up  
7407       April 3, 2017         NaN  2.3 and up  
7730        July 4, 2016         NaN  2.0 and up  
10342   January 31, 2017         NaN  3.0 and up

In [134]:
df1['Current Ver'].value_counts()

Varies with device    1299
1.0                    779
1.1                    254
1.2                    176
2.0                    148
                      ... 
2.9.10                   1
3.18.5                   1
1.3.A.2.9                1
9.9.1.1910               1
2.0.148.0                1
Name: Current Ver, Length: 2826, dtype: int64

In [135]:
# The data has no specific value to replace null entries with.
# Therefore, we will drop the 8 rows containing null values.

df1=df1[df1['Current Ver'].notna()]
df1.shape

(10268, 13)

**5) ANDROID VERSION**

In [136]:
df1[df1['Android Ver'].isnull()]

App         Category  Rating  \
4453                    [substratum] Vacuum: P  PERSONALIZATION     4.4   
4490                      Pi Dark [substratum]  PERSONALIZATION     4.5   
10472  Life Made WI-Fi Touchscreen Photo Frame              1.9    19.0   

         Reviews  Size  Installs  Type  Price Content Rating  \
4453       230.0  11.0    1000.0  Paid   1.49       Everyone   
4490       189.0   2.1   10000.0  Free   0.00       Everyone   
10472  3000000.0   0.0       NaN     0    NaN            NaN   

                  Genres    Last Updated Current Ver Android Ver  
4453     Personalization   July 20, 2018         4.4         NaN  
4490     Personalization  March 27, 2018         1.1         NaN  
10472  February 11, 2018          1.0.19  4.0 and up         NaN

In [137]:
df1['Android Ver'].value_counts()

4.1 and up            2355
4.0.3 and up          1437
4.0 and up            1322
Varies with device    1218
4.4 and up             889
2.3 and up             638
5.0 and up             543
4.2 and up             380
2.3.3 and up           279
2.2 and up             239
4.3 and up             234
3.0 and up             233
2.1 and up             131
1.6 and up             113
6.0 and up              57
7.0 and up              42
3.2 and up              36
2.0 and up              31
5.1 and up              22
1.5 and up              19
4.4W and up             11
3.1 and up              10
2.0.1 and up             7
8.0 and up               5
7.1 and up               3
4.0.3 - 7.1.1            2
5.0 - 8.0                2
1.0 and up               2
7.0 - 7.1.1              1
4.1 - 7.1.1              1
5.0 - 6.0                1
2.2 - 7.1.1              1
5.0 - 7.1.1              1
Name: Android Ver, dtype: int64

In [138]:
# There is no specific value to replace null entries with.
# Hence, we will drop the three rows containing null values.

df1=df1[df1['Android Ver'].notna()]
df1.shape

(10265, 13)

In [139]:
# A cross-check is performed to ensure that no remaining null values exist in the data.

table=pd.DataFrame(index=df1.columns)
table["datatype"]=df1.dtypes
table["not null values"]=df1.count()
table["null value"]=df1.isnull().sum()

table

datatype  not null values  null value
App              object            10265           0
Category         object            10265           0
Rating          float64            10265           0
Reviews         float64            10265           0
Size            float64            10265           0
Installs        float64            10265           0
Type             object            10265           0
Price           float64            10265           0
Content Rating   object            10265           0
Genres           object            10265           0
Last Updated     object            10265           0
Current Ver      object            10265           0
Android Ver      object            10265           0

### What all manipulations have you done and insights you found?

At first, I explored the data in the Play Store dataset and discovered the presence of null values and duplicate entries. To address these redundant data points, they should either be removed or managed using additional parameters.Also, I conducted a sanity check to ensure that the number of reviews was not greater than the number of installed users. Whenever possible, I handled the dataset by substituting null values with median values. In cases where there was no suitable replacement for the redundant data, I opted to drop those rows entirely from the dataset.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1

In [50]:
# Chart - 1 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 2

In [51]:
# Chart - 2 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 3

In [52]:
# Chart - 3 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 4

In [53]:
# Chart - 4 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 5

In [54]:
# Chart - 5 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 6

In [55]:
# Chart - 6 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 7

In [56]:
# Chart - 7 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 8

In [57]:
# Chart - 8 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 9

In [58]:
# Chart - 9 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 10

In [ ]:
# Chart - 10 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 11

In [ ]:
# Chart - 11 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 12

In [ ]:
# Chart - 12 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 13

In [ ]:
# Chart - 13 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 14 - Correlation Heatmap

In [ ]:
# Correlation Heatmap visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

#### Chart - 15 - Pair Plot

In [ ]:
# Pair Plot visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

## **SENTIMENT ANALYSIS**

### Dataset First View

In [140]:
df2.head()

App                                  Translated_Review  \
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...   
1  10 Best Foods for You    This help eating healthy exercise regular basis   
2  10 Best Foods for You                                                NaN   
3  10 Best Foods for You         Works great especially going grocery store   
4  10 Best Foods for You                                       Best idea us   

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
0  Positive                1.00                0.533333  
1  Positive                0.25                0.288462  
2       NaN                 NaN                     NaN  
3  Positive                0.40                0.875000  
4  Positive                1.00                0.300000

In [141]:
df2.tail()

App Translated_Review Sentiment  \
64290  Houzz Interior Design Ideas               NaN       NaN   
64291  Houzz Interior Design Ideas               NaN       NaN   
64292  Houzz Interior Design Ideas               NaN       NaN   
64293  Houzz Interior Design Ideas               NaN       NaN   
64294  Houzz Interior Design Ideas               NaN       NaN   

       Sentiment_Polarity  Sentiment_Subjectivity  
64290                 NaN                     NaN  
64291                 NaN                     NaN  
64292                 NaN                     NaN  
64293                 NaN                     NaN  
64294                 NaN                     NaN

In [142]:
rows = df2.shape[0]
col = df2.shape[1]
print(f"Play Store App Sentiment Analysis Dataset has {rows} rows and {col} columns")

Play Store App Sentiment Analysis Dataset has 64295 rows and 5 columns


### Dataset Information

In [143]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   App                     64295 non-null  object 
 1   Translated_Review       37427 non-null  object 
 2   Sentiment               37432 non-null  object 
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB


#### Duplicate Values

In [144]:
# Dataset Duplicate Value Count
len(df2[df2.duplicated()])

33616

Duplicate values in df2 are numerous, exceeding 30,000, suggesting that many columns contain NaN values.

In [145]:
df2.shape

(64295, 5)

#### Missing Values/Null Values

In [146]:
# Missing Values/Null Values Count
print(df2.isnull().sum())

App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64


In [147]:
# Visualizing the missing values
# Checking Null Value by plotting Heatmap
sns.heatmap(df2.isnull(), cmap='viridis', yticklabels=False)

<Axes: >

#### Understanding Your Variables

In [148]:
# Dataset Columns
df2.columns

Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='object')

In [149]:
# Dataset Describe
df2.describe(include='all')

App Translated_Review Sentiment  Sentiment_Polarity  \
count                 64295             37427     37432        37432.000000   
unique                 1074             27994         3                 NaN   
top     Angry Birds Classic              Good  Positive                 NaN   
freq                    320               247     23998                 NaN   
mean                    NaN               NaN       NaN            0.182146   
std                     NaN               NaN       NaN            0.351301   
min                     NaN               NaN       NaN           -1.000000   
25%                     NaN               NaN       NaN            0.000000   
50%                     NaN               NaN       NaN            0.150000   
75%                     NaN               NaN       NaN            0.400000   
max                     NaN               NaN       NaN            1.000000   

        Sentiment_Subjectivity  
count             37432.000000  
unique                     NaN  
top                        NaN  
freq                       NaN  
mean                  0.492704  
std                   0.259949  
min                   0.000000  
25%                   0.357143  
50%                   0.514286  
75%                   0.650000  
max                   1.000000

### Variables Description

**CUSTOMER REVIEW DATA**

This file contains the result of the sentiment analysis(emotional tone) conducted by the dataset creator. It has 64,295 rows of data with the following (5)columns:

App : Name of the app.

Translated_Review: Either the original review in English, or a translated version if the orignal review is not in English.

Sentiment: The result of the sentiment analysis conducted on a review. The value is either Positive, Neutral, or Negative.

Sentiment_Polarity: A value indicating the positivity or negativity of the sentiment, values range from -1 (most negative) to 1 (most positive).

Sentiment_Subjectivity: A value from 0 to 1 indicating the subjectivity of the review. Lower values indicate the review is based on factual information, and higher values indicate the review is based on personal or public opinions or judgements(subjective).

### Check Unique Values for each variable.

In [150]:
for column in df2.columns:
  unique_values = df2[column].nunique()
  print(f"No. of unique values in column {column} is {unique_values}.")

No. of unique values in column App is 1074.
No. of unique values in column Translated_Review is 27994.
No. of unique values in column Sentiment is 3.
No. of unique values in column Sentiment_Polarity is 5410.
No. of unique values in column Sentiment_Subjectivity is 4474.


### Data Wrangling

In [151]:
df2.isnull().sum()

App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64

In [152]:
nan_columns = []
nan_values = []

for column in df2.columns:
    nan_columns.append(column)
    nan_values.append(df2[column].isnull().sum())

fig, ax = plt.subplots(figsize=(8,4))
sns.barplot(x=nan_columns, y=nan_values)
plt.xticks(rotation=45)  # Rotate the x-axis labels
plt.title("Number of NaN values present in all columns")
plt.show()


In [153]:
## Merge a slice of the original dataset that contains App names and Types with corresponding apps in this dataset.
## As The presence of duplicate values can affect the accuracy and reliability of the analysis and results obtained from the dataset.
## And Before merging the dataset, we will drop all duplicate values.

In [154]:
#Dropping duplicate values
df2= df2.drop_duplicates()

In [155]:
df2= pd.merge(df2, df1[["App","Type"]] , how='inner', on="App")

# Drop null values from sentiment data
df2 = df2.dropna()

df2.shape

(40414, 6)

In order to obtain the values for the app column, I merge the dataset of the Play Store app reviews on the app and type columns using an inner join, then remove the missing values from the sentiment data.

### Data Vizualization

#### **Free vs Paid**

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

Answer Here.

# **Conclusion**

Write the conclusion here.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***